[alerting_v2] Use ES|QL Arrow helper in QueryService (#268588)
## Summary

This PR refactors the `QueryService` to use the ESQL Arrow helpers
exported by the ES JS client. Bug
https://github.com/elastic/elasticsearch-js/issues/3139 is fixed and
shipped in elasticsearch-js 9.4.0. With the fix, we can now use the
arrow helpers.

## Testing

1. Create a rule with the following query `FROM kibana_sample_data_logs`
2. Verify that you see the following error:

```
[2026-05-12T14:32:08.088+03:00][ERROR][plugins.alertingVTwo] illegal_argument_exception
	Root causes:
		illegal_argument_exception: ES|QL type [date_range] is not supported by the Arrow format
```

Fixes: https://github.com/elastic/rna-program/issues/479

---------

Co-authored-by: Cursor <cursoragent@cursor.com>
Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>
Co-authored-by: Elastic Machine <elasticmachine@users.noreply.github.com>